"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from django.contrib import messages
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-omi3e&&y+y^#f8rnb&)c5y8^hb4vb3g+657*cwmy#dqeqfbm!s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'application',
	'authcart',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templets"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'newdb',  # Replace with your PostgreSQL database name
        'USER': 'management',       # Replace with your PostgreSQL username
        'PASSWORD': 'likitha123',   # Replace with your PostgreSQL password
        'HOST': '127.0.0.1',           # Set to your PostgreSQL host, usually 'localhost'
        'PORT': '5432',                # Default port for PostgreSQL
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
#sending emails
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'ruttalalikitha@gmail.com'
EMAIL_HOST_PASSWORD = 'qhsu lrmr fhqi prjd'
EMAIL_PORT = 587
EMAIL_USE_TLS = True  # Corrected this setting
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
import os
STATIC_URL = 'static/'
STATICFILES_DIRS=[ 
	os.path.join(BASE_DIR,'static')
]

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,"media")
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MESSAGE_TAGS = {
      messages.ERROR: 'danger'
}

STRIPE_PUBLISHABLE_KEY = 'pk_test_51PtqFGLrJApHC3ioMw8RIVHDYkmXU9oYHEPcjWBxbN255hQKzWoP0n3g9T7kPio2exV37xK1XmV3p3u0RyKrp4s300q9IjZPbl'
STRIPE_SECRET_KEY = 'sk_test_51PtqFGLrJApHC3ioH85k58py7auaHEtF9z87OkQAGDPQArC9HREXuYjOphBXUwPsO56PJ3Mlfzijxoq7Cr9O6pWm00jOVpno19'


# settings.py
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
