# Generated by Django 5.1 on 2024-08-29 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('amount', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('address1', models.CharField(default='N/A', max_length=200)),
                ('address2', models.CharField(blank=True, default='N/A', max_length=200)),
                ('city', models.CharField(default='N/A', max_length=100)),
                ('state', models.CharField(default='N/A', max_length=100)),
                ('zip_code', models.CharField(default='N/A', max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('phone', models.CharField(default='N/A', max_length=100)),
                ('instamojo_response', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='images/images')),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('update_desc', models.CharField(max_length=5000)),
                ('delivered', models.BooleanField(default=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.orders')),
            ],
        ),
    ]
