# Generated by Django 5.1 on 2024-08-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='instamojo_response',
        ),
        migrations.AddField(
            model_name='orders',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
