# Generated by Django 5.1 on 2024-09-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_orders_amount_alter_orders_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='email',
            field=models.EmailField(max_length=90),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items_json',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zip_code',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.orders'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
